#!/usr/bin/env bash
TOPICS='data-input:1:1,data-output:1:1'
DOCKER_KAFKA_HOST=127.0.0.1
KAFKA_HOST_PORT=9092
DOCKER_KAFKA_PORTS="9092:$KAFKA_HOST_PORT"
ZOOKEEPER_HOST_PORT=2181
ZOOKEEPER_PORTS="2181:$ZOOKEEPER_HOST_PORT"
export DOCKER_KAFKA_HOST=$DOCKER_KAFKA_HOST TOPICS=$TOPICS DOCKER_KAFKA_PORTS=$DOCKER_KAFKA_PORTS ZOOKEEPER_PORTS=$ZOOKEEPER_PORTS

docker-compose up
